  # Site settings
title: BrisRuby
email: your-email@domain.com
description: >
  We're a motley bunch of friendly Rubyists based in South East Queensland.
  We get together at least monthly to talk, code, eat, and drink.
  If you are interested in Ruby or Rails, then come and join us!
location: >
  Our meetups are held at the Toowong Library on the fourth Tuesday of every month.
  Talks start at 6pm, intermission is around 7pm, and dinner from 9pm.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:title

url: "http://brisruby.org" # the base hostname & protocol for your site
twitter_username: brisruby
github_username:  brisruby

collections:
  meetups:
    output: true
    permalink: /meetups/:path
  people:
    output: true
    permalink: /people/:path

# Build settings
markdown: kramdown

kramdown:
  input: GFM
