# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'slim', :slim => { :pretty => true } do
  watch(%r'^[^_].+\.slim$')
  watch("_slides.html.slim") { |m| "layout.html.slim" }
end
