/*
 * Generated by dtrace(1M).
 */

#ifndef	_CUSTOM_PROBES_H
#define	_CUSTOM_PROBES_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define MATTCUSTOM_STABILITY "___dtrace_stability$mattcustom$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define MATTCUSTOM_TYPEDEFS "___dtrace_typedefs$mattcustom$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	MATTCUSTOM_ACTION_BEGIN(arg0) \
do { \
	__asm__ volatile(".reference " MATTCUSTOM_TYPEDEFS); \
	__dtrace_probe$mattcustom$action__begin$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " MATTCUSTOM_STABILITY); \
} while (0)
#define	MATTCUSTOM_ACTION_BEGIN_ENABLED() \
	({ int _r = __dtrace_isenabled$mattcustom$action__begin$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	MATTCUSTOM_ACTION_END() \
do { \
	__asm__ volatile(".reference " MATTCUSTOM_TYPEDEFS); \
	__dtrace_probe$mattcustom$action__end$v1(); \
	__asm__ volatile(".reference " MATTCUSTOM_STABILITY); \
} while (0)
#define	MATTCUSTOM_ACTION_END_ENABLED() \
	({ int _r = __dtrace_isenabled$mattcustom$action__end$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$mattcustom$action__begin$v1$63686172202a(const char *);
extern int __dtrace_isenabled$mattcustom$action__begin$v1(void);
extern void __dtrace_probe$mattcustom$action__end$v1(void);
extern int __dtrace_isenabled$mattcustom$action__end$v1(void);

#else

#define	MATTCUSTOM_ACTION_BEGIN(arg0) \
do { \
	} while (0)
#define	MATTCUSTOM_ACTION_BEGIN_ENABLED() (0)
#define	MATTCUSTOM_ACTION_END() \
do { \
	} while (0)
#define	MATTCUSTOM_ACTION_END_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _CUSTOM_PROBES_H */
