# Site settings
title: BrisRuby
email: your-email@domain.com
description: >
  We're a motely bunch of friendly Rubyists from based in South East Queensland.
  We get together at least monthly to talk, code, eat, and drink.  If you are interested in Ruby or Rails, then come and join us!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: brisruby
github_username:  brisruby

# Build settings
markdown: kramdown
